## See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Update hooks with `pre-commit autoupdate`
# Manually run with `pre-commit run --all-files`
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
      - id: check-case-conflict
  - repo: local
    hooks:
      - id: treefmt
        name: treefmt
        description: Format all files with treefmt
        entry: bash -c 'treefmt'
        language: system
        stages: ["pre-commit", "pre-push"]
