creation_rules:
  # This is encrypted/decrypted with multiple keys
  - path_regex: secrets.yaml
    key_groups:
      - age:
          # laptop
          - "age18mza76zktkr7extqze4dzxk3m5y6x5mxxqvp9prnexzhxac5x49qugq93u"

          # test
          - "age17t8ajhhpf5mhts7hn6n7khwzzgzhmgglkevnmn400s89vjn7fydstsrq3f"