creation_rules:
  # This is encrypted/decrypted with multiple keys
  - path_regex: secrets.yaml
    key_groups:
      - age:
          # laptop
          - "age18mza76zktkr7extqze4dzxk3m5y6x5mxxqvp9prnexzhxac5x49qugq93u"

          # test
          - "age17t8ajhhpf5mhts7hn6n7khwzzgzhmgglkevnmn400s89vjn7fydstsrq3f"

          # desktop
          - "age1ma56n47l8ljtw5vd97fzy0ap7p5k0r8gqec2gc8v2zqldvvyv40qxqp6dy"

          # family-server
          - "age199tynlg3jly5kalc0zfywrp4ncwjhg94xtqj6yxq3h38hgjwvy9sngska4"
