creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - age:
          - "age18mza76zktkr7extqze4dzxk3m5y6x5mxxqvp9prnexzhxac5x49qugq93u" # laptop
          - "age17t8ajhhpf5mhts7hn6n7khwzzgzhmgglkevnmn400s89vjn7fydstsrq3f" # test
          - "age1ma56n47l8ljtw5vd97fzy0ap7p5k0r8gqec2gc8v2zqldvvyv40qxqp6dy" # desktop
          - "age199tynlg3jly5kalc0zfywrp4ncwjhg94xtqj6yxq3h38hgjwvy9sngska4" # zephyr
          - "age1tlqfan6p7nldjnr83hdwnn7k7dpgjcrfemk2wxa8qgl79jkx5pas9a5ul0" # io
          - "age1dl8mh3rxyeav60pnwfdhyugvrgl4nqugy449rrc8p2jx0es36vksvmmf0v" # alethea
